name = "pavinfo-start"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "pavinfo-start-db"
database_id = "f3318cac-14fd-408e-9b27-5376b3693b21"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "pavinfo-start-assets"

[vars]
GOOGLE_REDIRECT_URI = "https://start.pavinfo.app/api/auth/google-callback"
AI_GATEWAY_ENDPOINT = "https://gateway.ai.cloudflare.com/v1/4392783e6cdaccb136cacda5f9800ba6/pav-cf-ai-gateway/compat"
